export const labels: Record<string, string> = {
  ACTIVE: "فعال",
  DRAFT: "پیش‌نویس",
  RESERVED: "رزرو",
  SOLD: "فروخته‌شده",
  RENTED: "اجاره‌شده",
  INACTIVE: "غیرفعال",
  ARCHIVED: "بایگانی",
  SALE: "فروش",
  RENT: "اجاره",
  MORTGAGE_RENT: "رهن و اجاره",
  PRESALE: "پیش‌فروش",
  APARTMENT: "آپارتمان",
  HOUSE: "خانه",
  VILLA: "ویلا",
  LAND: "زمین",
  COMMERCIAL: "تجاری",
  OFFICE: "اداری",
  STORE: "مغازه",
  WAREHOUSE: "انبار",
  OWNER: "مالک",
  APPLICANT: "متقاضی",
  BOTH: "مالک و متقاضی",
  LOW: "کم",
  NORMAL: "عادی",
  HIGH: "زیاد",
  IMMEDIATE: "فوری",
  PAUSED: "متوقف",
  FULFILLED: "تکمیل",
  CALL: "تماس",
  MESSAGE: "پیام",
  NOTE: "یادداشت",
  FOLLOW_UP: "پیگیری",
  MEETING: "جلسه",
  STATUS_CHANGE: "تغییر وضعیت",
  SCHEDULED: "برنامه‌ریزی‌شده",
  COMPLETED: "تکمیل‌شده",
  CANCELLED: "لغوشده",
  NO_SHOW: "عدم حضور",
  NEGOTIATION: "مذاکره",
  AGREED: "توافق اولیه",
  CONTRACTED: "قرارداد",
};
export const label = (v: string) => labels[v] ?? v;
