export const labels: Record<string, string> = {
  ACTIVE: "فعال",
  DRAFT: "پیش‌نویس",
  RESERVED: "رزرو",
  SOLD: "فروخته‌شده",
  RENTED: "اجاره‌شده",
  INACTIVE: "غیرفعال",
  ARCHIVED: "بایگانی",
  SALE: "فروش",
  RENT: "اجاره",
  MORTGAGE_RENT: "رهن و اجاره",
  PRESALE: "پیش‌فروش",
  APARTMENT: "آپارتمان",
  HOUSE: "خانه",
  VILLA: "ویلا",
  LAND: "زمین",
  COMMERCIAL: "تجاری",
  OFFICE: "اداری",
  STORE: "مغازه",
  WAREHOUSE: "انبار",
  OWNER: "مالک",
  APPLICANT: "متقاضی",
  BOTH: "مالک و متقاضی",
  LOW: "کم",
  NORMAL: "عادی",
  HIGH: "زیاد",
  IMMEDIATE: "فوری",
  PAUSED: "متوقف",
  FULFILLED: "تکمیل",
  CALL: "تماس",
  MESSAGE: "پیام",
  NOTE: "یادداشت",
  FOLLOW_UP: "پیگیری",
  MEETING: "جلسه",
  STATUS_CHANGE: "تغییر وضعیت",
  SCHEDULED: "برنامه‌ریزی‌شده",
  CONFIRMED: "تأییدشده",
  IN_PROGRESS: "در حال انجام",
  COMPLETED: "تکمیل‌شده",
  CANCELLED: "لغوشده",
  NO_SHOW: "عدم حضور",
  NEGOTIATION: "مذاکره",
  AGREED: "توافق اولیه",
  CONTRACTED: "قرارداد",
  PARTIALLY_RECEIVED: "بخشی وصول‌شده",
  RECEIVED: "وصول‌شده",
  VOID: "باطل‌شده",
  PENDING: "در انتظار",
  APPROVED: "تأییدشده",
  PAID: "تسویه‌شده",
  REVERSED: "برگشت‌خورده",
  CLEARED: "وصول‌شده",
  BOUNCED: "برگشتی",
  CASH: "نقدی",
  CARD: "کارت",
  TRANSFER: "واریز بانکی",
  CHECK: "چک",
  COMMISSION: "کمیسیون",
  DEPOSIT: "ودیعه / بیعانه",
  OTHER: "سایر",
  REFUND: "بازپرداخت",
  MANAGER: "مدیر داخلی",
  AGENT: "مشاور معامله",
  MARKETER: "بازاریاب / فایل‌یاب",
  CONTRACT_EXPERT: "کارشناس قرارداد",
  RECEPTIONIST: "پذیرش",
  ACCOUNTANT: "حسابدار",
  PHOTOGRAPHER: "عکاس",
  ON_LEAVE: "مرخصی",
  SUSPENDED: "تعلیق",
  ENDED: "پایان همکاری",
  NEW: "سرنخ جدید",
  CONTACTED: "تماس گرفته‌شده",
  QUALIFIED: "واجد شرایط",
  NEGOTIATING: "در حال مذاکره",
  CUSTOMER: "مشتری",
  LOST: "از دست‌رفته",
  UPLOADED: "بارگذاری‌شده",
  VERIFIED: "تأییدشده",
  REJECTED: "ردشده",
  EXPIRED: "منقضی‌شده",
  IMAGE: "تصویر",
  VIDEO: "ویدئو",
  FLOOR_PLAN: "پلان",
  VIRTUAL_TOUR: "تور مجازی",
  REFERRAL: "معرفی",
  FIELD_RESEARCH: "بازاریابی میدانی",
  WEBSITE: "وب‌سایت",
  SOCIAL_MEDIA: "شبکه اجتماعی",
  SUBMITTED: "ارسال‌شده",
  COUNTERED: "پیشنهاد متقابل",
  ACCEPTED: "پذیرفته‌شده",
  WITHDRAWN: "پس‌گرفته‌شده",
  OPEN: "باز",
  BANK: "بانک",
  PETTY_CASH: "تنخواه",
  INCOME: "درآمد",
  EXPENSE: "هزینه",
  RECEIVABLE: "دریافتنی",
  PAYABLE: "پرداختنی",
  RECEIPT: "دریافت وجه",
  PAYMENT: "پرداخت وجه",
  SALARY: "حقوق",
  PETTY_CASH_ADVANCE: "پرداخت تنخواه",
  PETTY_CASH_SETTLEMENT: "تسویه تنخواه",
  POSTED: "ثبت قطعی",
  SETTLED: "تسویه‌شده",
  REGISTERED: "ثبت‌شده",
  DEPOSITED: "واگذارشده به بانک",
  REVIEW: "در حال بازبینی",
  FINAL: "نسخه نهایی",
  SIGNED: "امضاشده",
  SELLER: "فروشنده",
  BUYER: "خریدار",
  LANDLORD: "موجر",
  TENANT: "مستأجر",
  GUARANTOR: "ضامن",
  WAIVED: "اسقاط‌شده",
  DISPUTED: "مورد اختلاف",
  PROVIDED: "ارائه‌شده",
  NOT_APPLICABLE: "فاقد موضوعیت",
  SIGNED_COPY: "نسخه امضاشده",
  IDENTITY: "مدارک هویتی",
  OWNERSHIP: "مدارک مالکیت",
};
export const label = (v: string) => labels[v] ?? v;
